import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const openDyslexicRegular = localFont({
  src: "./fonts/OpenDyslexicAlta-Regular.otf",
  variable: "--font-openDyslexic-Reg",
});

const verdana = localFont({
  src: "./fonts/Verdana.ttf",
  variable: "--verdana-Reg",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openDyslexicRegular.variable} ${verdana.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
